name: ct-book
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - numpy
    - matplotlib
    - seaborn
    - ipywidgets
    - pandas
    - sphinx-exercise
    - sphinx-inline-tabs
    - names
    - roboworld
    - jupyter-book
    - ghp-import
    - jupyterquiz
    - docutils==0.17.1
    - mdit-py-plugins~=0.3.1